baseURL = 'https://juicebar-demo.add1.dev/'
languageCode = 'en'
# languageCode = 'zh-CN'
theme = "JuiceBar"
title = "Meg's Blog"

[params]
author = "megaariii"
description = "My site description"
authorImage = "/images/profile.jpg"
paginate = 5

Title = "Mega Ari"
content = "Hi, nice to meet you!"
imageUrl = "/images/home.jpg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/megaariii"
[[params.social]]
name = "instagram"
url = "https://instagram.com/megaariii"
[[params.social]]
name = "twitter"
url = "https://twitter.com/megaariii"
[[params.social]]
name = "email"
url = "mailto:mega.ari186@gmail.com"

[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

[params.giscus]
repo = "megaariii/megs-blog"
repoID = "R_kgDOJ2ZhgA"
category = "Announcements"
categoryID = "DIC_kwDOJ2ZhgM4CXmfs"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



